services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=forums
    volumes:
      - PGDATA:/var/lib/postgresql/data

volumes:
  PGDATA:
    name: dbs
